package kodluyoruz.graduation.project.ui.view.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class AuthorCrudPopUpDesign extends VerticalLayout {
	protected HorizontalLayout hlLayoutAuthorId;
	protected Label lblAuthId;
	protected TextField txtAuthId;
	protected HorizontalLayout hlLayoutAuthName;
	protected Label lblAuthName;
	protected TextField txtAuthName;
	protected HorizontalLayout hlLayoutBookId2;
	protected Label lblAuthSurName;
	protected TextField txtAuthSurName;
	protected HorizontalLayout hlLayoutButtons;
	protected Button btnSave;
	protected Button btnUpdate;
	protected Button btnDelete;

	public AuthorCrudPopUpDesign() {
		Design.read(this);
	}
}
