package kodluyoruz.graduation.project.ui.view.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.DateField;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class BookCrudPopUpDesign extends VerticalLayout {
	protected HorizontalLayout hlLayoutBookId;
	protected Label lblBookId;
	protected TextField txtBookId;
	protected HorizontalLayout hlLayoutBookName;
	protected Label blBookName;
	protected TextField txtBookName;
	protected HorizontalLayout hlLayoutBookId1;
	protected Label lblBookAuthor;
	protected ComboBox<kodluyoruz.graduation.project.model.Author> cmbBookAuthor;
	protected HorizontalLayout hlLayoutBookDesc;
	protected Label lblBookDescription;
	protected TextField txtBookDescription;
	protected HorizontalLayout hlLayoutBookPageCount;
	protected Label lblBookPageCount;
	protected TextField txtBookPageCount;
	protected HorizontalLayout hlLayoutBookPublisher;
	protected Label lblBookPublisher;
	protected TextField txtBookPublisher;
	protected HorizontalLayout hlLayoutBookPublishDate;
	protected Label lblBookPublishinYear;
	protected DateField dfBookPublishingDate;
	protected HorizontalLayout hlLayoutBookCategory;
	protected Label lblBookCategory;
	protected ComboBox<kodluyoruz.graduation.project.enums.BookCategory> cmbBookCategory;
	protected HorizontalLayout hlLayoutBookNote;
	protected Label lblBookNote;
	protected TextField txtBookNote;
	protected HorizontalLayout hlLayoutButtons;
	protected Button btnSave;
	protected Button btnUpdate;
	protected Button btnDelete;

	public BookCrudPopUpDesign() {
		Design.read(this);
	}
}
