package kodluyoruz.graduation.project.ui.view.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class WelcomePageDesign extends AbsoluteLayout {
	protected Button btnCreateBook;
	protected Button btnDeleteBook;
	protected Button btnUpdateBook;
	protected Button btnSearchBook;
	protected Button btnApiList;

	public WelcomePageDesign() {
		Design.read(this);
	}
}
